language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - phpenv config-rm xdebug.ini
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - travis_retry composer update -n --prefer-dist --prefer-stable

script:
  - composer validate --strict --no-check-lock
  - composer update --dry-run

jobs:
  include:
    # Tests the lowest set of dependencies
    - php: 7.1
      install:
        - travis_retry composer update -n --prefer-lowest --prefer-stable --prefer-dist

    # Test against latest Symfony 3.4 stable
    - php: 7.4snapshot
      env: SYMFONY_REQUIRE="3.4.*"
      install:
        - travis_retry composer update -n --prefer-dist --prefer-stable

    # Test against latest Symfony 4.3 stable
    - php: 7.4snapshot
      env: SYMFONY_REQUIRE="4.3.*"
      install:
        - travis_retry composer update -n --prefer-dist --prefer-stable

    # Test against latest Symfony 4.4 stable
    - php: 7.4snapshot
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - travis_retry composer update -n --prefer-dist
